### ISSUE TITLE
Fails to connect to myob

### ISSUE THREAD

**Issue by bruced** [davidlumley/myob-api#15]
class MyobSessionsController < ApplicationController
  def new
      redirect_to myob_client.get_access_code_url
    end

    def create
      @token         = myob_client.get_access_token(params[:code])
      @company_files = myob_client.company_file.all
      # then show the user a view where they can log in to their company file
    end

    def myob_client
      @api_client = Myob::Api::Client.new({
        :consumer => {
          :key    => "u6785eurqcjv6wawgby7b3ag",
          :secret => "VmCkQxrMJwefmf5XYwKD5Zv7",
        },
      })
    end
end

routes
  resources :myob_sessions
  match "myob" => "myob_sessions#new", as: :myob_sessions_new, via: [:get, :post]

localhost:3000/myob

goes to myob login screen

then returns this screen

Your authorised applications
Allow access to your MYOB Account?
We have encountered some issue with the request, please try again later or contact your app support

    invalid_request

My registered apps
https://my.myob.com.au/Bd/pages/DevAppList.aspx

Application: mml
Key 	Secret 	Redirect Uri 	Usage (last 24 hr) 	Quota Limit 	Throttle Limit 	Action
u6785eurqcjv6wawgby7b3ag 	VmCkQxrMJwefmf5XYwKD5Zv7 	http://desktop 	2 	5000 per day 	2 per second 	Edit

What am i missing here?

**Comment by davidlumley** [comment]
Closing this issue as it looks like you're able to connect (either via the myob-api gem, or the omniauth-myob gem). If you run into another problem, please open another issue – thanks!

**Comment by ashish200025** [comment]
please let me know what wrong with my code

```
$postfield = array( 'client_id' => 'xxxx-xxxx-xxxx-xxxx-xxxxxxxx',
	'client_secret'=> '1xxxxIy1P97XBxxxxxxxx',
	'scope' => 'CompanyFile',
	'code' => 'WI_2!IAAAAP4Mclrxxxx-E_PShaJJQRBcJ32s_xiucnghEQEAAAEJ3vNaR5cwNjFYMH5mhcWI3mgve6XtVCv3SVoea9vH71w7eAKhCOOJUcX5dSKIiI_BEqlxwTEX_qswoXyoA6IPW1ytqIQKs-0JyyWtd9_i9vMUinV4xXNSd-JxFnUQvgT-LC9saqKfGy-2mxdTdbxIidXFnt7VsfH5Hcl2NDeo6wgukTRm2WfI9o0H_IHWfjhOtldDW9GLZ3UHz1g3yddajv7dmKjePlJQAqjrgjGxxxx7RT0gjGW3U7RT0cDTNYAR7V3TexxHeWxEz2MJr7BzdOQdcsn64RFynQXY-9h8J-qHufVCp--UJ97_Vnr5mXHnp8AS47aYb8raWy_upDjbUs1p_mmiZnQil8WHD2DiaAugd2ZVyxxxxA',
	'redirect_uri' => 'https://xyz.google.com/myob/webhook.php',
	'grant_type' =>'authorization_code' );
	
	
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL,"https://secure.myob.com/oauth2/v1/authorize");

curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS,  $postfield); 
$headers = [
	'Content-Type: application/x-www-form-urlencoded'
];
curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

$server_output = curl_exec ($ch);

 $info = curl_getinfo($ch);
// Check if any error occurred
if (curl_errno($ch)) {

  echo 'Took ', $info['total_time'], ' seconds to send a request to ', $info['url'], "\n";
}
curl_close ($ch);

echo '<pre>';
	print_r( json_decode( $server_output, true)  );
	//print_r(  $info  );
echo '</pre>';
```

i am getting error

Array
(
    [error] => invalid_request
)
