### ISSUE TITLE
Is local MYOB use possible? ie no omniauth?

### ISSUE THREAD

**Issue by liamgsmith** [davidlumley/myob-api#16]
Hi Guys.

Thanks for going to the effort of getting this gem going - hoping to help out as my skills improve.

Not an issue as such, just a Ruby newbie trying to find out if I can use the gem to pull data out of local MYOB files (via a Ruby script, not using Oauth/online site for callbacks)?

I can't quite get my head around how to initialise the API client via Myob::Api::Client.new if not using consumer secret/keys + tokens (does it matter?) to then be able to get through to the select_company_file method which looks like it reverts back to base64 username/password if a token doesn't exist (which is what I think I need to connect to the local file).

Is it a matter of using an empty :access_token to then trigger the base64 user/password? (Apologies, not at my windows machine at this point, just had the thought while typing the issue up!).

Any help much appreciated (or if I'm on the wrong track altogether),
Liam

**Comment by ghiculescu** [comment]
This gem is designed to talk to the online API. If you want to talk to a local company file programmatically, you are probably after the ODBC driver. http://developer.myob.com/resources/odbc-driver/

Alex Ghiculescu
alex@tanda.co

**Comment by sawilde** [comment]
Actually the REST API can be used to work against local ARL files; the ODBC driver that @ghiculescu refers to is for V19 only.

It's nearly the same except you don't pass/use the Bearer token in the requests - as such it would be easy to modify the gem to work in that way I would have thought. 

The issue will be in exposing the locally hosted API (usually on port 8080 but can be configured to run on another port). 

If you need more information on this I suggest you contact the MYOB API support team on their developer forums (you will need a developer account with MYOB).

**Comment by liamgsmith** [comment]
Thanks sawilde - correct, I've got the API services installed (ie PC / Server version of AccountRight), so just need to figure out how to create the right object, and tweak it to pass the base64 auth string vs the token so the rest of the gem performs as expected. 

ie - I'm connecting fine via httparty, I was just hoping to use the gem to speed up the rest of what I need to do rather than recreating it all.

I'll have a better look tonight and see if I can put some overrides in or see what's required.

**Comment by ghiculescu** [comment]
Ahh, cool. That's news to me. I imagine it would be a matter of changing the base URL in the gem - look in client.rb

I'm on the road but I'll have a look when I can. 

Alex Ghiculescu
alex@tanda.co

**Comment by sawilde** [comment]
That would be part of it and the other is skipping any oauth functionality when running `locally`

**Comment by liamgsmith** [comment]
Hi Guys.

I've managed to monkey patch enough to get reads working, but when I try for writes I end up in the oAuth areas and can't figure out how to work around it.

Apologies, I tried to fork, pull etc but I didn't really solve the issue, just worked around it and assume what I've done will break normal oAuth anyway. Hopefully I'll be able to circle back as my knowledge increases,
Cheers,
Liam

    ##################
    ## Monkey Patch ##
    module Myob
      module Api
        module Model
          class Base

           #Force URL
            #API_URL = 'https://api.myob.com/accountright/'
            API_URL = 'http://localhost:8080/AccountRight/'

          end
        end

        class Client
        	 def select_company_file(company_file)
               #Force id
    	        company_file_id = (company_file[:id])
    	        #company_file_id = self.company_file.first('Name' => company_file[:name])['Id']
    	        @current_company_file = {
    	          :id    => company_file_id,
    	          :token => company_file[:token] || Base64.encode64("#{company_file[:username]}:#{company_file[:password]}"),
    	        }
    	    end

    	    # # ISSUE IN HERE
    	    def connection
            if @refresh_token
              @auth_connection ||= OAuth2::AccessToken.new(@client, @access_token, {
                :refresh_token => @refresh_token
              }).refresh!
            else
            	##issue is here, which then leads to issue with .connection in the Base class
              @auth_connection ||= OAuth2::AccessToken.new(@client, @access_token)
            end
          end
        end
      end
    end

    ######################
